"""empty message

Revision ID: 954a726a681e
Revises: 5a3e20a9e20d
Create Date: 2019-09-24 19:32:56.458150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954a726a681e'
down_revision = '5a3e20a9e20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraisers', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE fundraisers SET last_modified_at = created_at")
    op.alter_column('fundraisers', 'last_modified_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraisers', 'last_modified_at')
    # ### end Alembic commands ###
