"""empty message

Revision ID: ce7b856bc59d
Revises: 22bb36ffc124
Create Date: 2019-10-04 20:22:26.343741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7b856bc59d'
down_revision = 'c58942fe6b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraisers', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraisers', 'image_url')
    # ### end Alembic commands ###
